name: Build and Test- Main Branch

on:
  push:
    branches:
      - master

jobs:
  # Build_Test_and_Run:
  #   runs-on: self-hosted

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   #- name: Set up Docker Buildx
  #   #  uses: docker/setup-buildx-action@v3

  #   - name: Build Test Image
  #     run: docker build -t dematicscrewfixtrenthamwmstodb:testing -f Dockerfile.testing . --progress=plain --no-cache

  #   - name: Run Tests
  #     run: docker run --rm dematicscrewfixtrenthamwmstodb:testing npm run test

  Build_Image:
    runs-on: self-hosted
    # needs: Build_Test_and_Run

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: dematicscrewfixtrenthaSorterJourneys
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t dematicscrewfixtrenthamsorterjourneys:latest -f Dockerfile . --progress=plain --no-cache

      - name: Push Image
        run: |
          docker tag dematicscrewfixtrenthamsorterjourneys:latest jwlyons/dematicscrewfixtrenthamsorterjourneys:latest
          docker push jwlyons/dematicscrewfixtrenthamsorterjourneys:latest
          docker tag dematicscrewfixtrenthamsorterjourneys:latest jwlyons/dematicscrewfixtrenthamsorterjourneys:${{ steps.metadata.outputs.version }}
          docker push jwlyons/dematicscrewfixtrenthamsorterjourneys:${{ steps.metadata.outputs.version }}

      - name: Remove Docker Images
        run: |
          docker rmi dematicscrewfixtrenthamsorterjourneys:latest
          docker rmi jwlyons/dematicscrewfixtrenthamsorterjourneys:latest
          docker rmi jwlyons/dematicscrewfixtrenthamsorterjourneys:${{ steps.metadata.outputs.version }}
